# Generated by Django 5.1.4 on 2024-12-10 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_rooms_delete_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='category',
            field=models.CharField(default='Python', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rooms',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='members',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='room_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
